# Import secrets from local .env file 
spring.config.import=optional:file:.env[.properties]

spring.application.name=nanourl
server.port=8080

# PostgreSQL (production database)
spring.config.activate.on-profile=prod
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Logging
logging.level.com.eugene7997.nanourl=INFO
logging.level.org.springframework=WARN